FROM python:3.12

# 設定工作目錄
WORKDIR /app

# 安裝基本系統工具
# 如需要使用mysqlclient來連線到mysqlclient，需要安裝編譯mysqlclient時所需要的系統庫
# RUN apt-get install -y --no-install-recommends \
#     default-libmysqlclient-dev \
#     pkg-config
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 複製依賴清單到/app/下
COPY requirements.txt .

# 升級 pip 並安裝套件
RUN python -m pip install  --no-cache-dir -U pip setuptools wheel && \
    python -m pip install --no-cache-dir -r requirements.txt

# 複製原始碼
COPY ./src/__init__.py ./src/__init__.py
COPY ./src/task/__init__.py ./src/task/__init__.py
COPY ./src/pages ./src/pages
COPY ./src/task/core ./src/task/core
COPY ./src/util ./src/util
COPY ./src/app.py ./src/app.py
COPY ./.streamlit ./.streamlit

# Streamlit預設監聽8501，但因以後要遷移到 cloud run service 執行，
# 為了配合cloud Run service 習慣，提醒開放 8080。
EXPOSE 8080

# 啟動指令：--server.address=0.0.0.0 是容器化運行的關鍵、讓streamlit監聽所有網路介面
# 開放 8080 port 靠下面這行
CMD ["streamlit", "run", "src/app.py", "--server.port=8080", "--server.address=0.0.0.0"]
