FROM apache/airflow:3.1.7-python3.12

# 不強制寫WORKDIR，因為會預設使用/opt/airflow
# EXPOSE 8080不用寫，因為本就預設8080或是yml檔那邊會寫
# 不需要寫COPY /dags、/task複製程式碼，因為啟動容器時會用mounting技術

# 安裝基本系統工具
# 如需要使用mysqlclient來連線到mysqlclient，需要安裝編譯mysqlclient時所需要的系統庫
# RUN apt-get install -y --no-install-recommends \
#     default-libmysqlclient-dev \
#     pkg-config
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /requirements.txt
RUN python -m pip install --no-cache-dir -U pip setuptools wheel && \
    python -m pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt