FROM python:3.12

# 設定工作目錄
WORKDIR /app

# 安裝基本系統工具
# 如需要使用mysqlclient來連線到mysqlclient，需要安裝編譯mysqlclient時所需要的系統庫
# RUN apt-get install -y --no-install-recommends \
#     default-libmysqlclient-dev \
#     pkg-config
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 複製依賴清單到/app/下
COPY requirements.txt .

# 升級 pip 並安裝套件
RUN python -m pip install  --no-cache-dir -U pip setuptools wheel && \
    python -m pip install --no-cache-dir -r requirements.txt

# 複製原始碼 (note: 這行是為了讓image沒有掛載時也能獨立運作，但是compose.yml中有寫會用volume覆蓋，所以實際上以yml描述為主)
COPY ./src ./src
COPY ./.streamlit ./.streamlit

# Streamlit預設監聽8501，
# 但因為以後要遷移streamlit到cloud run執行，為了配合cloud Run習慣，在啟動指令中指定監聽8080
# Compose.yml要記得寫streamlit容器內8080映射到主機8080
EXPOSE 8080

# 啟動指令：--server.address=0.0.0.0 是容器化運行的關鍵、讓streamlit監聽所有網路介面
CMD ["streamlit", "run", "src/app.py", "--server.port=8080", "--server.address=0.0.0.0"]