name: Deploy-Streamlit-to-Cloud-Run

on:
  push:
    branches: [ "UAT" ] # 當代碼推送到UAT時觸發

jobs:
  # Job 1: 打包 Docker Image 並推送到 Artifact Registry
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_JSONKEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker asia-east1-docker.pkg.dev
        # 將Google的SA餵給這台虛擬機裡的Docker，讓它在執行 docker push 時，知道要帶著SA權限去使用Artifact Registry。

        # 建立標籤，指向Artifact Registry 倉庫
      - name: Build and Push Image
        run: |
          IMAGE_TAG="asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/traffic-web-service/streamlit-app:latest"
          docker build -f docker/Dockerfile.streamlit -t $IMAGE_TAG .
          docker push $IMAGE_TAG

  # Job 2: 部署到 Cloud Run 並連接 VPC Connector
  deploy-to-cloud-run:
    needs: build-and-push # 確保 Image 推送成功後才開始部署
    runs-on: ubuntu-latest
    steps:
      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_JSONKEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy streamlit-service \
            --image="asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/traffic-web-service/streamlit-app:latest" \
            --region=asia-east1 \
            --platform=managed \
            --vpc-connector=streamlit-vpc-connector \
            --allow-unauthenticated \
            --set-env-vars="MYSQL_HOST=10.140.0.14" \
            --set-env-vars="MYSQL_PORT=${{ secrets.MYSQL_PORT }}" \
            --set-env-vars="MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" \
            --set-env-vars="MYSQL_USER=${{ secrets.MYSQL_USER }}" \
            --set-env-vars="MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" \
            --set-env-vars="REDIS_HOST=10.140.0.14" \
            --set-env-vars="REDIS_PORT=${{ secrets.REDIS_PORT }}" \
            --set-env-vars="REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" \
            --set-env-vars="GOOGLE_MAP_API_KEY=${{ secrets.GOOGLE_MAP_API_KEY }}"